languageCode = "en-us"
title = "datawookie"
theme = "wookie"
baseurl = "https://datawookie.netlify.com/"

googleAnalytics = "UA-89552291-2"

paginate = 30

# Limit number of entries in RSS feeds.
#
rssLimit = 20

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = ""
author = "Andrew B. Collier"
# logoimage = "images/logo.jpg"
# copyright = "foo"
twitterAuthor = "@datawookie"
# twitterSite = "@invalid_input"

[permalinks]
blog  = "/blog/:year/:month/:slug/"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 3
name = "Résumé"
url = "/resume/"